kind: pipeline
type: docker
name: build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: dockerconfig
    host:
      path: /root/.docker/
  - name: netrc
    host:
      path: /root/.netrc
  - name: kubeconfig
    host:
      path: /root/.kube/
  - name: gopathcache
    host:
      path: /data/docker-drone-runner-volume/global-gopath

trigger:
  event:
    exclude:
      - promote
      - tag
      - "pull_request"

image_pull_secrets:
  - dockerconfig

# node:
  # machine: testing

environment:
  APPNAME: ${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}
  LOCAL_IMAGE: ${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}:${CI_COMMIT_BRANCH}
  APP_IMAGE: registry.cn-wulanchabu.aliyuncs.com/gouboyun/${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}:${CI_COMMIT_BRANCH}
  APP_IMAGE_IID: registry.cn-wulanchabu.aliyuncs.com/gouboyun/${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}:${CI_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}

steps:
  - name: app
    image: registry.cn-wulanchabu.aliyuncs.com/gouboyun-pub/golang-swag-go-micro-v5:1.26-alpine
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: dockerconfig
        path: /root/.docker/
      - name: gopathcache
        path: /drone/gopath
      - name: netrc
        path: /root/.netrc
    environment:
      GOPATH: /drone/gopath
      GOPROXY: https://goproxy.cn,https://goproxy.io,direct
      GOPRIVATE: git.gouboyun.tv
      CGO_ENABLED: 0
    commands:
      - GOARCH=amd64 go build -tags timetzdata -ldflags "-extldflags -static -X main.GitRev=${DRONE_COMMIT_SHA}" -o app-amd64
      - GOARCH=arm64 go build -tags timetzdata -ldflags "-extldflags -static -X main.GitRev=${DRONE_COMMIT_SHA}" -o app-arm64

  - name: build-push-image
    image: m.daocloud.io/docker.io/docker:24.0.7-git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: dockerconfig
        path: /root/.docker/
    when:
      branch:
        - master
        - i18n
        - testing
    commands:
      - "docker buildx build --platform linux/amd64,linux/arm64 -t $APP_IMAGE -t $APP_IMAGE_IID --push ."

  - name: deploy-testing
    image: m.daocloud.io/docker.io/docker:24.0.7-git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: docker-profile
        path: /root/.docker/
    when:
      branch:
        - testing
    commands:
      - docker rm -f $APPNAME || true
      - docker run --restart always -itd --network eagle -e MICRO_REGISTRY=etcd -e MICRO_REGISTRY_ADDRESS=etcd --name $APPNAME --hostname $APPNAME $APP_IMAGE_IID

  - name: deploy-prod
    image: uhub.service.ucloud.cn/moryapub/helm-kubectl:3.16.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: docker-profile
        path: /root/.docker/
      - name: kubeconfig
        path: /root/.kube
    environment:
      KUBECONFIG: /root/.kube/config
    when:
      branch:
        - master

    commands:
      - kubectl set image --record deployment/$APPNAME $APPNAME=$APP_IMAGE_IID
