// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: geoippb.proto

package geoippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Province string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *CityResult) Reset() {
	*x = CityResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geoippb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityResult) ProtoMessage() {}

func (x *CityResult) ProtoReflect() protoreflect.Message {
	mi := &file_geoippb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityResult.ProtoReflect.Descriptor instead.
func (*CityResult) Descriptor() ([]byte, []int) {
	return file_geoippb_proto_rawDescGZIP(), []int{0}
}

func (x *CityResult) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CityResult) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CityResult) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type ReqLookup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ReqLookup) Reset() {
	*x = ReqLookup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geoippb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLookup) ProtoMessage() {}

func (x *ReqLookup) ProtoReflect() protoreflect.Message {
	mi := &file_geoippb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLookup.ProtoReflect.Descriptor instead.
func (*ReqLookup) Descriptor() ([]byte, []int) {
	return file_geoippb_proto_rawDescGZIP(), []int{1}
}

func (x *ReqLookup) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RspLookup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CityResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RspLookup) Reset() {
	*x = RspLookup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geoippb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspLookup) ProtoMessage() {}

func (x *RspLookup) ProtoReflect() protoreflect.Message {
	mi := &file_geoippb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspLookup.ProtoReflect.Descriptor instead.
func (*RspLookup) Descriptor() ([]byte, []int) {
	return file_geoippb_proto_rawDescGZIP(), []int{2}
}

func (x *RspLookup) GetResult() *CityResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReqLookupBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip []string `protobuf:"bytes,1,rep,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ReqLookupBatch) Reset() {
	*x = ReqLookupBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geoippb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLookupBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLookupBatch) ProtoMessage() {}

func (x *ReqLookupBatch) ProtoReflect() protoreflect.Message {
	mi := &file_geoippb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLookupBatch.ProtoReflect.Descriptor instead.
func (*ReqLookupBatch) Descriptor() ([]byte, []int) {
	return file_geoippb_proto_rawDescGZIP(), []int{3}
}

func (x *ReqLookupBatch) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

type RspLookupBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*CityResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *RspLookupBatch) Reset() {
	*x = RspLookupBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geoippb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspLookupBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspLookupBatch) ProtoMessage() {}

func (x *RspLookupBatch) ProtoReflect() protoreflect.Message {
	mi := &file_geoippb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspLookupBatch.ProtoReflect.Descriptor instead.
func (*RspLookupBatch) Descriptor() ([]byte, []int) {
	return file_geoippb_proto_rawDescGZIP(), []int{4}
}

func (x *RspLookupBatch) GetResult() []*CityResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_geoippb_proto protoreflect.FileDescriptor

var file_geoippb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x22, 0x56, 0x0a, 0x0a, 0x43, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x1b, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x38, 0x0a,
	0x09, 0x52, 0x73, 0x70, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6f,
	0x69, 0x70, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x3d, 0x0a, 0x0e, 0x52, 0x73, 0x70,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2b, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65,
	0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x7e, 0x0a, 0x05, 0x47, 0x65, 0x6f, 0x69,
	0x70, 0x12, 0x32, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x12, 0x2e, 0x67, 0x65,
	0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x1a,
	0x12, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x52, 0x73, 0x70, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0b, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x17, 0x2e,
	0x67, 0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x52, 0x73, 0x70, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x67,
	0x65, 0x6f, 0x69, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geoippb_proto_rawDescOnce sync.Once
	file_geoippb_proto_rawDescData = file_geoippb_proto_rawDesc
)

func file_geoippb_proto_rawDescGZIP() []byte {
	file_geoippb_proto_rawDescOnce.Do(func() {
		file_geoippb_proto_rawDescData = protoimpl.X.CompressGZIP(file_geoippb_proto_rawDescData)
	})
	return file_geoippb_proto_rawDescData
}

var file_geoippb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geoippb_proto_goTypes = []interface{}{
	(*CityResult)(nil),     // 0: geoippb.CityResult
	(*ReqLookup)(nil),      // 1: geoippb.ReqLookup
	(*RspLookup)(nil),      // 2: geoippb.RspLookup
	(*ReqLookupBatch)(nil), // 3: geoippb.ReqLookupBatch
	(*RspLookupBatch)(nil), // 4: geoippb.RspLookupBatch
}
var file_geoippb_proto_depIdxs = []int32{
	0, // 0: geoippb.RspLookup.result:type_name -> geoippb.CityResult
	0, // 1: geoippb.RspLookupBatch.result:type_name -> geoippb.CityResult
	1, // 2: geoippb.Geoip.Lookup:input_type -> geoippb.ReqLookup
	3, // 3: geoippb.Geoip.LookupBatch:input_type -> geoippb.ReqLookupBatch
	2, // 4: geoippb.Geoip.Lookup:output_type -> geoippb.RspLookup
	4, // 5: geoippb.Geoip.LookupBatch:output_type -> geoippb.RspLookupBatch
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_geoippb_proto_init() }
func file_geoippb_proto_init() {
	if File_geoippb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geoippb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geoippb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLookup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geoippb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspLookup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geoippb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLookupBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geoippb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspLookupBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geoippb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoippb_proto_goTypes,
		DependencyIndexes: file_geoippb_proto_depIdxs,
		MessageInfos:      file_geoippb_proto_msgTypes,
	}.Build()
	File_geoippb_proto = out.File
	file_geoippb_proto_rawDesc = nil
	file_geoippb_proto_goTypes = nil
	file_geoippb_proto_depIdxs = nil
}
