// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: geoippb.proto

package geoippb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Geoip service

func NewGeoipEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Geoip service

type GeoipService interface {
	Lookup(ctx context.Context, in *ReqLookup, opts ...client.CallOption) (*RspLookup, error)
	LookupBatch(ctx context.Context, in *ReqLookupBatch, opts ...client.CallOption) (*RspLookupBatch, error)
}

type geoipService struct {
	c    client.Client
	name string
}

func NewGeoipService(name string, c client.Client) GeoipService {
	return &geoipService{
		c:    c,
		name: name,
	}
}

func (c *geoipService) Lookup(ctx context.Context, in *ReqLookup, opts ...client.CallOption) (*RspLookup, error) {
	req := c.c.NewRequest(c.name, "Geoip.Lookup", in)
	out := new(RspLookup)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoipService) LookupBatch(ctx context.Context, in *ReqLookupBatch, opts ...client.CallOption) (*RspLookupBatch, error) {
	req := c.c.NewRequest(c.name, "Geoip.LookupBatch", in)
	out := new(RspLookupBatch)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Geoip service

type GeoipHandler interface {
	Lookup(context.Context, *ReqLookup, *RspLookup) error
	LookupBatch(context.Context, *ReqLookupBatch, *RspLookupBatch) error
}

func RegisterGeoipHandler(s server.Server, hdlr GeoipHandler, opts ...server.HandlerOption) error {
	type geoip interface {
		Lookup(ctx context.Context, in *ReqLookup, out *RspLookup) error
		LookupBatch(ctx context.Context, in *ReqLookupBatch, out *RspLookupBatch) error
	}
	type Geoip struct {
		geoip
	}
	h := &geoipHandler{hdlr}
	return s.Handle(s.NewHandler(&Geoip{h}, opts...))
}

type geoipHandler struct {
	GeoipHandler
}

func (h *geoipHandler) Lookup(ctx context.Context, in *ReqLookup, out *RspLookup) error {
	return h.GeoipHandler.Lookup(ctx, in, out)
}

func (h *geoipHandler) LookupBatch(ctx context.Context, in *ReqLookupBatch, out *RspLookupBatch) error {
	return h.GeoipHandler.LookupBatch(ctx, in, out)
}
